// Auto-generated by dev-server.js
module.exports = {
  apps: [
    {
      name: 'estelle-relay-dev',
      script: 'packages/relay/dist/bin.js',
      cwd: 'C:\\WorkSpace\\estelle2',
      watch: false,
      autorestart: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3000'
      }
    },
    {
      name: 'estelle-pylon-dev',
      script: 'packages/pylon/dist/bin.js',
      cwd: 'C:\\WorkSpace\\estelle2',
      watch: false,
      autorestart: true,
      env: {
        NODE_ENV: 'development',
        ESTELLE_ENV_CONFIG: "{\"envId\":2,\"pylon\":{\"deviceId\":\"1\",\"relayUrl\":\"ws://localhost:3000\",\"configDir\":\"C:\\\\Users\\\\LINEGAMES\\\\.claude-dev\",\"credentialsBackupDir\":\"C:\\\\Users\\\\LINEGAMES\\\\.claude-credentials\\\\dev\",\"dataDir\":\"C:\\\\WorkSpace\\\\estelle2\\\\dev-data\",\"mcpPort\":9878},\"beacon\":{\"enabled\":true,\"host\":\"127.0.0.1\",\"port\":9875,\"env\":\"dev\",\"reconnect\":true,\"reconnectInterval\":3000}}"
      }
    }
  ]
};
